import { randomUUID } from "node:crypto";
import { appendJsonl } from "../project/jsonl.js";
import { projectPaths } from "../project/paths.js";
import { allocateProjectVersion } from "../project/versions.js";
import { checkEvidenceSufficiency } from "../core/evidence-policy.js";
import { loadLedger, readProject } from "../research/ledger.js";
import { allParadigms, finalizeWorkflow, type WorkflowResult, type WorkflowSpec } from "./spec.js";

export const expertReviewWorkflowSpec: WorkflowSpec = { id: "expert-review", version: "1.0.0", description: "Run four independent review roles and produce evidence-grounded recommendations for human approval.", paradigms: allParadigms, steps: [{ id: "evidence", role: "verifier", effect: "read", description: "load and check the evidence ledger" }, { id: "method", role: "analyst", effect: "read", description: "review methods and claims" }, { id: "ethics", role: "critic", effect: "read", description: "review integrity, uncertainty, and ethics" }, { id: "editorial", role: "writer", effect: "read", description: "propose clarity and reporting revisions" }], requiredArtifacts: ["expert-review.md", "review-result.json", "review-suggestions.json"] };
export const expertReviewSpec = expertReviewWorkflowSpec;
export interface ReviewerRole { id: "methodologist" | "evidence-auditor" | "integrity-ethicist" | "editor"; label: string; remit: string; }
export const DEFAULT_REVIEWER_ROLES: readonly ReviewerRole[] = [{ id: "methodologist", label: "Methodologist", remit: "methods, design, and conclusion boundaries" }, { id: "evidence-auditor", label: "Evidence auditor", remit: "claim, source, locator, and conflict coverage" }, { id: "integrity-ethicist", label: "Integrity and ethics reviewer", remit: "uncertainty, ethics, privacy, and reporting risks" }, { id: "editor", label: "Academic editor", remit: "clarity, structure, and transparent revision suggestions" }];
export interface ReviewApproval { approved: boolean; actor: string; reason: string; at?: string }
export interface ExpertReviewOptions { approval?: ReviewApproval; roles?: readonly ReviewerRole[] }
export interface ExpertReviewSuggestion { id: string; role: ReviewerRole["id"]; priority: "block" | "warn"; target?: string; suggestion: string; rationale: string; status: "proposed" }

export async function runExpertReview(root: string, options: ExpertReviewOptions = {}): Promise<WorkflowResult> {
  const project = await readProject(root); const ledger = await loadLedger(root); const gates = checkEvidenceSufficiency({ ...ledger, paradigm: project.paradigm });
  const version = await allocateProjectVersion(root, "manuscript-revision", `expert-review:${Date.now()}`); const approval = options.approval;
  if (!approval?.approved) gates.push({ gateId: "expert-review:human-approval", ok: false, severity: "block", reason: "human approval is required before adopting review recommendations" });
  const suggestions: ExpertReviewSuggestion[] = [];
  for (const claim of ledger.claims) { const gate = gates.find((item) => item.claimIds?.includes(claim.id)); if (claim.status === "supported" && gate && !gate.ok) suggestions.push({ id: `suggestion_${randomUUID().replaceAll("-", "")}`, role: "evidence-auditor", priority: "block", target: claim.id, suggestion: "downgrade or substantiate this claim", rationale: "the evidence gate does not pass", status: "proposed" }); if (claim.kind !== "result" && /\b(?:causes?|leads? to|proves?|established)\b/i.test(claim.text)) suggestions.push({ id: `suggestion_${randomUUID().replaceAll("-", "")}`, role: "methodologist", priority: "warn", target: claim.id, suggestion: "replace causal or confirmatory wording with evidence-qualified language", rationale: "the claim is not a verified result artifact", status: "proposed" }); }
  if (suggestions.length === 0) suggestions.push({ id: `suggestion_${randomUUID().replaceAll("-", "")}`, role: "editor", priority: "warn", suggestion: "retain the current text and document the human review decision", rationale: "no automatic revision is performed by this workflow", status: "proposed" });
  const result = { schemaVersion: "psyclaw/expert-review/v1", version, workflowVersion: expertReviewWorkflowSpec.version, roles: options.roles ?? DEFAULT_REVIEWER_ROLES, approval: approval ? { ...approval, at: approval.at ?? new Date().toISOString() } : { status: "pending" }, suggestions, findingCount: suggestions.length };
  const markdown = [`# Expert Review ${version}`, "", `Research goal: ${project.goal}`, "", "Recommendations are proposals only; this workflow never edits manuscript text.", "", "## Recommendations", "", ...suggestions.map((item) => `- [${item.priority}] ${item.role}: ${item.suggestion}${item.target ? ` (${item.target})` : ""}`), ""].join("\n");
  const receipt = { schemaVersion: "psyclaw/review-receipt/v1", runId: `review:${version}`, workflow: expertReviewWorkflowSpec.id, version, approval: approval?.approved ? "approved" : "pending", actor: approval?.actor ?? null, idempotencyKey: `expert-review:${version}`, createdAt: new Date().toISOString() };
  await appendJsonl(projectPaths(root).audit, { schemaVersion: "psyclaw/audit/v1", action: "expert-review", workflow: expertReviewWorkflowSpec.id, version, approval: receipt.approval, actor: receipt.actor, receipt: receipt.schemaVersion, at: receipt.createdAt });
  return finalizeWorkflow(root, expertReviewWorkflowSpec, { gates, outputs: [{ path: "expert-review.md", contents: markdown }, { path: "review-result.json", contents: `${JSON.stringify(result, null, 2)}\n` }, { path: "review-suggestions.json", contents: `${JSON.stringify({ schemaVersion: "psyclaw/review-suggestions/v1", version, suggestions }, null, 2)}\n` }, { path: `expert-review-${version}.md`, contents: markdown }, { path: `review-receipt-${version}.json`, contents: `${JSON.stringify(receipt, null, 2)}\n` }], completed: ["four reviewer roles evaluated the ledger", "standardized review result produced", "revision suggestions recorded without editing source text"] });
}
