import { lstat, readFile, readdir } from "node:fs/promises";
import { join } from "node:path";
import { assertSafeProjectPath } from "./paths.js";

/**
 * Shared manuscript discovery (convention: docs/文档规范.md).
 *
 * The panel, the publish workflow, and the agent tools all resolve "the
 * manuscript" the same way so a document generated by any of them is
 * immediately recognized by the others:
 *   1. notes/manuscript.md   (panel-managed)
 *   2. paper/ or docs/ *.md  (prefer names like 手稿/论文/初稿/draft/manuscript)
 *   3. report fallbacks      (meta-analysis / literature review / HANDOFF)
 */

export const MANUSCRIPT_NAME_PATTERN = /(手稿|论文|初稿|draft|manuscript|Draft|Manuscript)/i;

export interface Manuscript {
  exists: boolean;
  path: string | null;
  markdown: string;
}

export async function findMarkdownManuscript(root: string): Promise<{ path: string; markdown: string } | null> {
  for (const dir of ["paper", "docs"]) {
    let entries: import("node:fs").Dirent[] = [];
    try { entries = await readdir(join(root, dir), { withFileTypes: true }); } catch { continue; }
    const candidates: Array<{ name: string; mtimeMs: number }> = [];
    for (const entry of entries) {
      if (!entry.isFile() || !/\.(md|markdown)$/i.test(entry.name)) continue;
      const stat = await lstat(join(root, dir, entry.name)).catch(() => undefined);
      if (stat?.isFile()) candidates.push({ name: entry.name, mtimeMs: stat.mtimeMs });
    }
    const preferred = candidates.filter((candidate) => MANUSCRIPT_NAME_PATTERN.test(candidate.name));
    const pool = preferred.length > 0 ? preferred : candidates;
    pool.sort((left, right) => right.mtimeMs - left.mtimeMs);
    const picked = pool[0];
    if (!picked) continue;
    const path = `${dir}/${picked.name}`;
    try {
      return { path, markdown: await readFile(await assertSafeProjectPath(root, path), "utf8") };
    } catch { /* try next candidate */ }
  }
  return null;
}

export async function readManuscript(root: string): Promise<Manuscript> {
  // 1. The panel-managed working copy wins when present.
  try {
    const target = await assertSafeProjectPath(root, "notes/manuscript.md");
    const markdown = await readFile(target, "utf8");
    return { exists: true, path: "notes/manuscript.md", markdown };
  } catch { /* fall through */ }
  // 2. A real manuscript under paper/ or docs/ is the next best source.
  const found = await findMarkdownManuscript(root);
  if (found) return { exists: true, path: found.path, markdown: found.markdown };
  // 3. Report fallbacks only when no manuscript exists at all.
  const candidates = [
    "analysis/outputs/meta-analysis.md",
    "outputs/literature-review.md",
    "notes/HANDOFF.md",
  ];
  for (const relative of candidates) {
    try {
      const target = await assertSafeProjectPath(root, relative);
      const markdown = await readFile(target, "utf8");
      return { exists: true, path: relative, markdown };
    } catch { /* try next candidate */ }
  }
  return { exists: false, path: null, markdown: "" };
}
